#!/bin/bash
cd /home/dx/project/discover-plus/build
export LD_LIBRARY_PATH=./bin:$LD_LIBRARY_PATH
export QT_QUICK_CONTROLS_STYLE=Material
export QT_QUICK_CONTROLS_MATERIAL_THEME=Dark
export QT_QUICK_CONTROLS_MATERIAL_VARIANT=Dense
export QT_QUICK_CONTROLS_MATERIAL_ACCENT="#82B1FF"
export QT_QUICK_CONTROLS_MATERIAL_PRIMARY="#448AFF"
export QT_QUICK_CONTROLS_MATERIAL_BACKGROUND="#121212"
export QT_QUICK_CONTROLS_MATERIAL_FOREGROUND="#FFFFFF"
./bin/plasma-discover "$@"