/*
 *   SPDX-FileCopyrightText: 2025-2026 DXVSI <https://github.com/DXVSI>
 *
 *   SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
 */

#include "CoprClient.h"
#include "libdiscover_backend_packagekit_debug.h"

#include <KLocalizedString>
#include <KOSRelease>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QLocale>
#include <QNetworkRequest>
#include <QRegularExpression>
#include <QSettings>
#include <QSysInfo>
#include <QTimeZone>
#include <QTimer>
#include <QUrl>
#include <QUrlQuery>

#include <functional>

namespace DiscoverVersion
{
// contains the static QLatin1String version definition
// autogenerated from top CMakeLists.txt
#include "DiscoverVersion.h"
}

#if defined(WITH_MARKDOWN)
extern "C" {
#include <mkdio.h>
}
#endif

// The only place that knows where COPR lives
static QString coprHubUrl()
{
    return QStringLiteral("https://copr.fedorainfracloud.org");
}

static QByteArray coprUserAgent()
{
    return QByteArrayLiteral("DiscoverPlus/") + QByteArray(DiscoverVersion::version.data(), DiscoverVersion::version.size())
        + QByteArrayLiteral(" (+https://github.com/DXVSI/discover-plus)");
}

// application/json or anything from the +json family, with or without parameters such as charset
static bool isJsonMediaType(const QString &contentType)
{
    const QString mediaType = contentType.section(QLatin1Char(';'), 0, 0).trimmed().toLower();
    return mediaType == QLatin1String("application/json") || mediaType.endsWith(QLatin1String("+json"));
}

// Maps QSysInfo::currentCpuArchitecture() to the RPM basearch used in chroot names
static QString rpmBaseArch(const QString &cpuArchitecture)
{
    if (cpuArchitecture == QLatin1String("arm64")) {
        return QStringLiteral("aarch64");
    }
    if (cpuArchitecture == QLatin1String("arm")) {
        return QStringLiteral("armhfp");
    }
    if (cpuArchitecture == QLatin1String("power64")) {
        return QSysInfo::ByteOrder == QSysInfo::LittleEndian ? QStringLiteral("ppc64le") : QStringLiteral("ppc64");
    }

    static const QStringList sameInRpm = {
        QStringLiteral("x86_64"),
        QStringLiteral("i386"),
        QStringLiteral("s390x"),
        QStringLiteral("riscv64"),
        QStringLiteral("loongarch64"),
    };
    return sameInRpm.contains(cpuArchitecture) ? cpuArchitecture : QString();
}

// The dnf copr plugin lets a distribution declare which COPR chroots it uses:
// [main] distribution and releasever, read in this order, later files win
static void readDnfCoprOverrides(QString &distribution, QString &releasever)
{
    QStringList files = {
        QStringLiteral("/usr/share/dnf/plugins/copr.vendor.conf"),
        QStringLiteral("/etc/dnf/plugins/copr.vendor.conf"),
        QStringLiteral("/etc/dnf/plugins/copr.conf"),
    };
    const QDir dropInDir(QStringLiteral("/etc/dnf/plugins/copr.d"));
    const QStringList dropIns = dropInDir.entryList({QStringLiteral("*.conf")}, QDir::Files, QDir::Name);
    for (const QString &dropIn : dropIns) {
        files.append(dropInDir.filePath(dropIn));
    }

    for (const QString &file : std::as_const(files)) {
        if (!QFile::exists(file)) {
            continue;
        }
        const QSettings config(file, QSettings::IniFormat);
        const QString fileDistribution = config.value(QStringLiteral("main/distribution")).toString().trimmed();
        if (!fileDistribution.isEmpty()) {
            distribution = fileDistribution;
        }
        const QString fileReleasever = config.value(QStringLiteral("main/releasever")).toString().trimmed();
        if (!fileReleasever.isEmpty()) {
            releasever = fileReleasever;
        }
    }
}

CoprClient::CoprClient(QObject *parent)
    : QObject(parent)
    , m_baseUrl(coprHubUrl() + QStringLiteral("/api_3"))
    , m_networkAccessManager(new QNetworkAccessManager(this))
{
    m_currentChroot = detectCurrentChroot();

    if (m_currentChroot.isEmpty()) {
        qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient: could not detect the COPR chroot of this system (os-release ID:" << KOSRelease().id()
                                                      << "VERSION_ID:" << KOSRelease().versionId() << "CPU:" << QSysInfo::currentCpuArchitecture()
                                                      << "). A distribution other than fedora is only trusted when it is declared in the dnf copr plugin"
                                                      << "configuration. COPR availability is unknown: projects are not filtered and installs are not blocked.";
    } else {
        qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient initialized. Chroot:" << m_currentChroot;
    }
}

CoprClient::~CoprClient()
{
    cancelAllRequests();
}

// Same logic as the dnf5 copr plugin (copr_config.cpp): <distribution>-<releasever>-<arch>
// from the plugin configuration, else from os-release, where Fedora Rawhide is
// recognised by REDHAT_SUPPORT_PRODUCT_VERSION because its VERSION_ID is numeric.
// dnf5 hands that name to the server, which picks the chroot. We compare it with
// chroot names ourselves, so an os-release ID of a Fedora derivative ("nobara-42")
// would match nothing, hide every project and refuse every install. Only "fedora"
// and what the distribution itself declared for dnf are trusted; anything else
// is an unknown chroot.
QString CoprClient::detectCurrentChroot() const
{
    QString distribution;
    QString releasever;
    readDnfCoprOverrides(distribution, releasever);

    const KOSRelease osRelease;
    if (distribution.isEmpty()) {
        distribution = osRelease.id();
        if (distribution != QLatin1String("fedora")) {
            return {};
        }
    }
    if (releasever.isEmpty()) {
        releasever = osRelease.versionId();
        if (distribution == QLatin1String("fedora") && osRelease.extraValue(QStringLiteral("REDHAT_SUPPORT_PRODUCT_VERSION")) == QLatin1String("rawhide")) {
            releasever = QStringLiteral("rawhide");
        }
    }

    const QString arch = rpmBaseArch(QSysInfo::currentCpuArchitecture());
    if (releasever.isEmpty() || arch.isEmpty()) {
        return {};
    }

    return QStringLiteral("%1-%2-%3").arg(distribution, releasever, arch);
}

QUrl CoprClient::projectWebUrl(const QString &owner, const QString &project)
{
    // Group projects are owned by "@group" in the API but live under /coprs/g/<group>/
    if (owner.startsWith(QLatin1Char('@'))) {
        return QUrl(QStringLiteral("%1/coprs/g/%2/%3/").arg(coprHubUrl(), owner.mid(1), project));
    }
    return QUrl(QStringLiteral("%1/coprs/%2/%3/").arg(coprHubUrl(), owner, project));
}

// Letters, digits and "_.+-" only, never a leading "-" or ".": nothing that a command
// line could take for an option, a path or a separator of the repository id.
// \z and not $, which would let a trailing newline pass.
static bool isValidCoprName(const QString &name)
{
    static const QRegularExpression pattern(QStringLiteral("\\A[A-Za-z0-9_][A-Za-z0-9_.+-]{0,127}\\z"));
    return pattern.match(name).hasMatch();
}

bool CoprClient::isValidOwnerName(const QString &owner)
{
    return isValidCoprName(owner.startsWith(QLatin1Char('@')) ? owner.mid(1) : owner);
}

bool CoprClient::isValidProjectName(const QString &project)
{
    return isValidCoprName(project);
}

bool CoprClient::isValidPackageName(const QString &packageName)
{
    return isValidCoprName(packageName);
}

QString CoprClient::repositoryId(const QString &owner, const QString &project)
{
    if (!isValidOwnerName(owner) || !isValidProjectName(project)) {
        return {};
    }
    const QString repoOwner = owner.startsWith(QLatin1Char('@')) ? QStringLiteral("group_") + owner.mid(1) : owner;
    return QStringLiteral("copr:%1:%2:%3").arg(QUrl(coprHubUrl()).host(), repoOwner, project);
}

QString CoprClient::dnfProjectSpec(const QString &owner, const QString &project)
{
    if (!isValidOwnerName(owner) || !isValidProjectName(project)) {
        return {};
    }
    return QStringLiteral("%1/%2/%3").arg(QUrl(coprHubUrl()).host(), owner, project);
}

void CoprClient::searchProjects(const QString &query, int limit, int offset)
{
    QString endpoint = QStringLiteral("/project/search");
    QUrl url(m_baseUrl + endpoint);

    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("query"), query);
    urlQuery.addQueryItem(QStringLiteral("limit"), QString::number(limit));
    urlQuery.addQueryItem(QStringLiteral("offset"), QString::number(offset));
    url.setQuery(urlQuery);

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient: Searching projects, query:" << query << "limit:" << limit << "offset:" << offset;
    queueRequest({url, QStringLiteral("searchProjects")});
}

void CoprClient::getProject(const QString &owner, const QString &project)
{
    QString endpoint = QStringLiteral("/project");
    QUrl url(m_baseUrl + endpoint);

    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("ownername"), owner);
    urlQuery.addQueryItem(QStringLiteral("projectname"), project);
    url.setQuery(urlQuery);

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient: Looking up project" << owner << "/" << project;
    queueRequest({url, QStringLiteral("getProject")});
}

void CoprClient::getLatestProjects(int limit, int offset, bool byName)
{
    QString endpoint = QStringLiteral("/project/list");
    QUrl url(m_baseUrl + endpoint);

    // The server defaults to order_type=ASC (the oldest projects), so the
    // order has to be explicit. There is no server-side maximum for limit.
    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("limit"), QString::number(limit));
    urlQuery.addQueryItem(QStringLiteral("offset"), QString::number(offset));
    urlQuery.addQueryItem(QStringLiteral("order"), byName ? QStringLiteral("name") : QStringLiteral("id"));
    urlQuery.addQueryItem(QStringLiteral("order_type"), byName ? QStringLiteral("ASC") : QStringLiteral("DESC"));
    url.setQuery(urlQuery);

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient: Getting latest projects:" << url.toString();
    queueRequest({url, QStringLiteral("getLatestProjects")});
}

// Project and package names are taken from the query of the request and never from
// a joined string: COPR allows characters in them that any separator would clash with
static QString queryItem(const QUrl &url, const QString &key)
{
    return QUrlQuery(url).queryItemValue(key, QUrl::FullyDecoded);
}

static QString packagePagesKey(const QString &owner, const QString &project)
{
    return owner + QLatin1Char('/') + project;
}

void CoprClient::getProjectPackages(const QString &owner, const QString &project)
{
    // One run through the pages at a time: its result is a signal that everybody hears,
    // and a second run would mix its pages into the same list
    const QString key = packagePagesKey(owner, project);
    if (m_packagePages.contains(key)) {
        qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR package list of" << key << "is already being fetched";
        return;
    }
    m_packagePages.insert(key, {});
    requestProjectPackagesPage(owner, project, 0);
}

void CoprClient::requestProjectPackagesPage(const QString &owner, const QString &project, int offset)
{
    QString endpoint = QStringLiteral("/package/list");
    QUrl url(m_baseUrl + endpoint);

    // The default order of the server is the package id, oldest first. There is no
    // total in the answer: a page that comes back full is followed by the next one.
    // with_latest_succeeded_build gives the version and the dates of what can really be
    // installed, but costs the server a query per package: only this request has it.
    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("ownername"), owner);
    urlQuery.addQueryItem(QStringLiteral("projectname"), project);
    urlQuery.addQueryItem(QStringLiteral("with_latest_build"), QStringLiteral("True"));
    urlQuery.addQueryItem(QStringLiteral("with_latest_succeeded_build"), QStringLiteral("True"));
    urlQuery.addQueryItem(QStringLiteral("limit"), QString::number(PackagesPageSize));
    urlQuery.addQueryItem(QStringLiteral("offset"), QString::number(offset));
    urlQuery.addQueryItem(QStringLiteral("order"), QStringLiteral("name"));
    urlQuery.addQueryItem(QStringLiteral("order_type"), QStringLiteral("ASC"));
    url.setQuery(urlQuery);

    queueRequest({url, projectPackagesRequestType(), true});
}

QUrl CoprClient::projectMonitorUrl(const QString &owner, const QString &project) const
{
    QString endpoint = QStringLiteral("/monitor");
    QUrl url(m_baseUrl + endpoint);

    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("ownername"), owner);
    urlQuery.addQueryItem(QStringLiteral("projectname"), project);
    url.setQuery(urlQuery);
    return url;
}

void CoprClient::getProjectMonitor(const QString &owner, const QString &project, bool forOpenPage)
{
    queueRequest({projectMonitorUrl(owner, project), projectMonitorRequestType(), forOpenPage});
}

bool CoprClient::getProjectMonitorLazily(const QString &owner, const QString &project)
{
    const QUrl url = projectMonitorUrl(owner, project);

    // What the cache still has costs the server nothing
    const auto cached = m_cache.constFind(url.toString());
    const bool isCached = cached != m_cache.cend() && QDateTime::currentMSecsSinceEpoch() - cached->timestamp < cached->ttlMs;
    if (isLazyPaused() && !isCached) {
        return false;
    }

    queueRequest({url, projectMonitorRequestType(), false, true});
    return true;
}

void CoprClient::dropLazyProjectMonitor(const QString &owner, const QString &project)
{
    const QUrl url = projectMonitorUrl(owner, project);
    for (auto it = m_lazyQueue.begin(); it != m_lazyQueue.end(); ++it) {
        if (it->url == url) {
            const Request dropped = *it;
            m_lazyQueue.erase(it);
            qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Dropped lazy COPR request, still queued:" << m_lazyQueue.size();
            cancelRequest(dropped);
            return;
        }
    }
}

bool CoprClient::isLazyPaused() const
{
    return qMax(m_lazyPausedUntilMs, m_retryNotBeforeMs) > QDateTime::currentMSecsSinceEpoch();
}

void CoprClient::noteLazyResult(bool failed)
{
    if (!failed) {
        m_lazyFailuresInARow = 0;
        return;
    }
    if (++m_lazyFailuresInARow < MaxLazyFailuresInARow) {
        return;
    }

    // Something is wrong with the server or the network: list items stop asking for
    // a while. Open pages and an explicit retry are not held back by this.
    m_lazyFailuresInARow = 0;
    m_lazyPausedUntilMs = QDateTime::currentMSecsSinceEpoch() + qint64(LazyPauseSecs) * 1000;
    qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << MaxLazyFailuresInARow << "lazy COPR requests failed in a row - none for" << LazyPauseSecs << "s";
    cancelLazyQueue();
}

void CoprClient::cancelLazyQueue()
{
    // Cancelled and not failed: nothing was sent, the list items simply have no answer yet
    const auto dropped = std::exchange(m_lazyQueue, {});
    for (const Request &request : dropped) {
        cancelRequest(request);
    }
}

void CoprClient::cancelStreamRequests()
{
    QList<Request> cancelled;

    for (auto it = m_activeReplies.begin(); it != m_activeReplies.end();) {
        const QPointer<QNetworkReply> reply = *it;
        if (reply && reply->property("forOpenPage").toBool()) {
            ++it;
            continue;
        }
        if (reply) {
            cancelled.append({reply->request().url(), reply->property("requestType").toString()});
            if (reply->property("lazy").toBool() && m_activeLazyRequests > 0) {
                --m_activeLazyRequests;
            }
            reply->disconnect(this);
            reply->abort();
            reply->deleteLater();
        }
        it = m_activeReplies.erase(it);
        if (m_activeRequests > 0) {
            --m_activeRequests;
        }
    }

    cancelled.append(std::exchange(m_lazyQueue, {}));

    for (auto it = m_requestQueue.begin(); it != m_requestQueue.end();) {
        if (it->forOpenPage) {
            ++it;
            continue;
        }
        cancelled.append(*it);
        it = m_requestQueue.erase(it);
    }

    // Answers that were deferred to the event loop (cache hits, refusals) are cancelled
    // too, except those for an open application page
    ++m_requestGeneration;

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Cancelled" << cancelled.size() << "COPR list requests, kept for open pages:" << m_activeReplies.size()
                                                << "active and" << m_requestQueue.size() << "queued";

    // Only now: whoever hears about a cancellation may ask again at once
    for (const Request &request : std::as_const(cancelled)) {
        cancelRequest(request);
    }
    processNextRequest();
}

void CoprClient::cancelAllRequests()
{
    for (const auto &reply : std::as_const(m_activeReplies)) {
        if (reply) {
            reply->disconnect(this);
            reply->abort();
            reply->deleteLater();
        }
    }
    m_activeReplies.clear();
    m_requestQueue.clear();
    m_lazyQueue.clear();
    m_packagePages.clear();
    m_activeRequests = 0;
    m_activeLazyRequests = 0;
    // Answers that were deferred to the event loop (cache hits, refusals) are cancelled too
    ++m_requestGeneration;

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Cancelled all COPR pending requests";
}

void CoprClient::cancelRequest(const Request &request)
{
    if (request.requestType != projectPackagesRequestType() && request.requestType != projectMonitorRequestType()) {
        return;
    }
    const QString owner = queryItem(request.url, QStringLiteral("ownername"));
    const QString project = queryItem(request.url, QStringLiteral("projectname"));
    if (request.requestType == projectPackagesRequestType()) {
        m_packagePages.remove(packagePagesKey(owner, project));
    }
    Q_EMIT projectRequestCancelled(request.requestType, owner, project);
}

void CoprClient::queueRequest(const Request &request)
{
    const QUrl url = request.url;
    const QString requestType = request.requestType;
    QString urlString = url.toString();

    // A request that was deferred to the event loop is dropped by a cancellation that
    // happens in between, unless an open application page is waiting for it
    const auto deferred = [this, request](const std::function<void()> &answer) {
        QTimer::singleShot(0, this, [this, request, answer, generation = m_requestGeneration]() {
            if (request.forOpenPage || generation == m_requestGeneration) {
                answer();
            } else {
                cancelRequest(request);
            }
        });
    };

    // Check cache first
    if (m_cache.contains(urlString)) {
        const CacheEntry &entry = m_cache[urlString];
        qint64 now = QDateTime::currentMSecsSinceEpoch();
        if (now - entry.timestamp < entry.ttlMs) {
            qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR cache hit for:" << requestType;
            deferred([this, request, json = entry.data]() {
                emitResultForRequest(request, json);
            });
            return;
        }
        m_cache.remove(urlString);
    }

    // The server asked us to back off (HTTP 429/503): do not send anything until then
    const QString backOff = backOffMessage();
    if (!backOff.isEmpty()) {
        deferred([this, request, backOff]() {
            failRequest(request, backOff);
        });
        return;
    }

    // Deduplication - skip if same URL already queued or in flight. The answer is a
    // signal that everybody hears, so nobody is left waiting. The URL carries the
    // variant and the offset of a request, so different pages never merge.
    for (auto it = m_requestQueue.begin(); it != m_requestQueue.end(); ++it) {
        if (it->url == url) {
            qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR request deduped, already queued:" << requestType << urlString;
            if (request.forOpenPage && !it->forOpenPage) {
                // Asked again by an open page: goes to the front like a new request of it would
                m_requestQueue.erase(it);
                break;
            }
            return;
        }
    }
    for (const auto &reply : std::as_const(m_activeReplies)) {
        if (reply && reply->property("urlString").toString() == urlString) {
            qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR request deduped, already in flight:" << requestType << urlString;
            if (request.forOpenPage) {
                reply->setProperty("forOpenPage", true);
            }
            // Somebody is really waiting for it now
            if (!request.lazy && reply->property("lazy").toBool()) {
                reply->setProperty("lazy", false);
                m_activeLazyRequests = qMax(0, m_activeLazyRequests - 1);
            }
            return;
        }
    }
    for (auto it = m_lazyQueue.begin(); it != m_lazyQueue.end(); ++it) {
        if (it->url == url) {
            // Asked again: lazily it becomes the newest, otherwise it stops being lazy
            m_lazyQueue.erase(it);
            break;
        }
    }

    if (request.lazy) {
        m_lazyQueue.append(request);
        if (m_lazyQueue.size() > MaxLazyQueueLength) {
            // The oldest one belongs to a row that was scrolled past long ago
            cancelRequest(m_lazyQueue.takeFirst());
        }
    } else if (request.forOpenPage) {
        // The user is looking at that page: before what lists and searches queued
        const auto firstOther = std::find_if(m_requestQueue.begin(), m_requestQueue.end(), [](const Request &queued) {
            return !queued.forOpenPage;
        });
        m_requestQueue.insert(firstOther, request);
    } else {
        m_requestQueue.enqueue(request);
    }
    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Queued COPR request:" << requestType << "queue size:" << m_requestQueue.size()
                                                << "lazy:" << m_lazyQueue.size();

    if (m_activeRequests < MaxConcurrentRequests) {
        processNextRequest();
    }
}

void CoprClient::emitResultForRequest(const Request &request, const QJsonObject &json)
{
    const QString &requestType = request.requestType;
    if (requestType == QStringLiteral("searchProjects") || requestType == QStringLiteral("getLatestProjects")) {
        Q_EMIT projectsFound(parseProjectsResponse(json));
        return;
    }
    if (requestType == QStringLiteral("getProject")) {
        Q_EMIT projectFound(parseProjectObject(json));
        return;
    }

    const QString owner = queryItem(request.url, QStringLiteral("ownername"));
    const QString project = queryItem(request.url, QStringLiteral("projectname"));

    if (requestType == projectMonitorRequestType()) {
        bool complete = true;
        const QList<CoprPackageInfo> packages = parseMonitorResponse(json, owner, project, &complete);
        Q_EMIT projectMonitorFound(owner, project, packages, complete);
    } else if (requestType == projectPackagesRequestType()) {
        const int offset = queryItem(request.url, QStringLiteral("offset")).toInt();
        const QString key = packagePagesKey(owner, project);
        const QList<CoprPackageInfo> page = parsePackagesResponse(json, owner, project);

        // Every end of a run (result, failure, cancellation) removes what it collected
        QList<CoprPackageInfo> packages = m_packagePages.take(key);
        packages.append(page);

        const bool fullPage = page.size() >= PackagesPageSize;
        if (fullPage && packages.size() < MaxPackagesPerProject) {
            m_packagePages.insert(key, packages);
            requestProjectPackagesPage(owner, project, offset + PackagesPageSize);
            return;
        }
        m_packagePages.remove(key);
        if (fullPage) {
            qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR project" << key << "has more than" << packages.size() << "packages, keeping these";
        }
        Q_EMIT projectPackagesFound(owner, project, packages, !fullPage);
    }
}

void CoprClient::failRequest(const Request &request, const QString &errorMessage)
{
    const QString &requestType = request.requestType;
    qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR request" << requestType << "failed:" << errorMessage;
    if (requestType == QStringLiteral("getProject")) {
        Q_EMIT projectNotFound(queryItem(request.url, QStringLiteral("ownername")), queryItem(request.url, QStringLiteral("projectname")));
        return;
    }
    Q_EMIT errorOccurred(requestType, errorMessage);

    if (requestType == QStringLiteral("searchProjects") || requestType == QStringLiteral("getLatestProjects")) {
        // The list ends here; the message above tells the user why
        Q_EMIT projectsFound(QList<CoprProjectInfo>());
    } else if (requestType == projectPackagesRequestType() || requestType == projectMonitorRequestType()) {
        // Never an empty result: a project without packages is something else than
        // a request that can be repeated
        const QString owner = queryItem(request.url, QStringLiteral("ownername"));
        const QString project = queryItem(request.url, QStringLiteral("projectname"));
        if (requestType == projectPackagesRequestType()) {
            m_packagePages.remove(packagePagesKey(owner, project));
        }
        Q_EMIT projectRequestFailed(requestType, owner, project, errorMessage);
    }
}

QString CoprClient::backOffMessage() const
{
    const qint64 retryInMs = m_retryNotBeforeMs - QDateTime::currentMSecsSinceEpoch();
    if (retryInMs <= 0) {
        return {};
    }
    const int retryInSecs = int((retryInMs + 999) / 1000);
    return i18np("COPR asked to wait before sending more requests. Try again in %1 second.",
                 "COPR asked to wait before sending more requests. Try again in %1 seconds.",
                 retryInSecs);
}

void CoprClient::storeInCache(const Request &request, const QJsonObject &json, qint64 size)
{
    // The eviction below keeps the newest entry, so it could never make this one fit
    if (size > MaxCacheBytes) {
        qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR response of" << size << "bytes is larger than the cache, not caching it";
        return;
    }

    // Only what a search found lives longer: lists, packages and monitors say what is
    // there and what can be installed right now
    const bool isSearch = request.requestType == QStringLiteral("searchProjects") || request.requestType == QStringLiteral("getProject");
    const qint64 now = QDateTime::currentMSecsSinceEpoch();
    m_cache.insert(request.url.toString(), CacheEntry{json, now, size, isSearch ? SearchCacheTtlMs : CacheTtlMs});

    // A project list page is about 0.5 MB and its URL is rarely asked for twice,
    // so nothing else would ever remove it: drop what expired, then the oldest
    // entries until the cache fits.
    m_cache.removeIf([now](const std::pair<const QString &, CacheEntry &> &entry) {
        return now - entry.second.timestamp >= entry.second.ttlMs;
    });

    qint64 totalSize = 0;
    for (const CacheEntry &entry : std::as_const(m_cache)) {
        totalSize += entry.size;
    }
    while (totalSize > MaxCacheBytes && m_cache.size() > 1) {
        auto oldest = m_cache.begin();
        for (auto it = m_cache.begin(); it != m_cache.end(); ++it) {
            if (it->timestamp < oldest->timestamp) {
                oldest = it;
            }
        }
        totalSize -= oldest->size;
        m_cache.erase(oldest);
    }
}

void CoprClient::noteRetryAfter(const QNetworkReply *reply)
{
    // Retry-After is either a number of seconds or an HTTP date
    const QByteArray retryAfter = reply->rawHeader("Retry-After").trimmed();
    const qint64 now = QDateTime::currentMSecsSinceEpoch();

    // The deadline is kept in milliseconds: an HTTP date rounded down to whole
    // seconds would let the next request out up to a second too early
    bool isNumber = false;
    const qint64 seconds = retryAfter.toLongLong(&isNumber);
    qint64 waitMs = qint64(DefaultRetryAfterSecs) * 1000;
    if (isNumber) {
        waitMs = qBound(qint64(0), seconds, qint64(MaxRetryAfterSecs)) * 1000;
    } else {
        QString httpDate = QString::fromLatin1(retryAfter);
        httpDate.chop(httpDate.endsWith(QLatin1String(" GMT")) ? 4 : 0);
        QDateTime date = QLocale::c().toDateTime(httpDate, QStringLiteral("ddd, dd MMM yyyy hh:mm:ss"));
        date.setTimeZone(QTimeZone::UTC);
        if (date.isValid()) {
            waitMs = date.toMSecsSinceEpoch() - now;
        }
    }

    waitMs = qBound(qint64(1000), waitMs, qint64(MaxRetryAfterSecs) * 1000);
    m_retryNotBeforeMs = qMax(m_retryNotBeforeMs, now + waitMs);
    qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR asked to back off, Retry-After:" << retryAfter << "- no COPR requests for" << waitMs << "ms";
}

void CoprClient::processNextRequest()
{
    // While the server wants us to back off, what is already queued must not reach
    // it either
    const QString backOff = backOffMessage();
    if (!backOff.isEmpty()) {
        const auto dropped = std::exchange(m_requestQueue, {});
        const quint64 generation = m_requestGeneration;
        for (const auto &request : dropped) {
            // Whoever hears about a failure may cancel the list requests: that includes
            // the rest of these, but never what an open page is waiting for
            if (generation != m_requestGeneration && !request.forOpenPage) {
                cancelRequest(request);
            } else {
                failRequest(request, backOff);
            }
        }
        cancelLazyQueue();
        return;
    }

    while (m_activeRequests < MaxConcurrentRequests) {
        Request requestData;
        if (!m_requestQueue.isEmpty()) {
            requestData = m_requestQueue.dequeue();
        } else if (!m_lazyQueue.isEmpty() && m_activeLazyRequests < MaxConcurrentLazyRequests) {
            requestData = m_lazyQueue.takeLast();
            ++m_activeLazyRequests;
        } else {
            break;
        }
        const QUrl url = requestData.url;
        const QString requestType = requestData.requestType;
        const QString urlString = url.toString();

        QNetworkRequest request(url);
        request.setRawHeader("Accept", "application/json");
        // Identify ourselves: without it Qt sends "Mozilla/5.0", which the COPR bot protection treats as a browser
        request.setHeader(QNetworkRequest::UserAgentHeader, coprUserAgent());

        QNetworkReply *reply = m_networkAccessManager->get(request);
        reply->setProperty("requestType", requestType);
        reply->setProperty("urlString", urlString);
        reply->setProperty("forOpenPage", requestData.forOpenPage);
        reply->setProperty("lazy", requestData.lazy);

        m_activeReplies.append(reply);
        ++m_activeRequests;

        qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Processing COPR request via Qt network:" << requestType << "active:" << m_activeRequests
                                                    << "queued:" << m_requestQueue.size();

        // Search costs the server 6-8 s; a project list page is a few hundred KB (about 3 s on a good link);
        // a full page of packages with their latest succeeded builds takes 2-3 s
        int timeoutMs = 10000;
        if (requestType == QStringLiteral("searchProjects")) {
            timeoutMs = 25000;
        } else if (requestType == QStringLiteral("getLatestProjects") || requestType == projectPackagesRequestType()) {
            timeoutMs = 20000;
        }
        QTimer::singleShot(timeoutMs, reply, [reply]() {
            if (reply->isRunning()) {
                reply->setProperty("timedOut", true);
                reply->abort();
            }
        });

        // The monitor has no pagination. The server needs more than the timeout before the
        // first byte for a project of thousands of packages; this stops what comes faster.
        if (requestType == projectMonitorRequestType()) {
            connect(reply, &QNetworkReply::downloadProgress, reply, [reply](qint64 received) {
                if (received > MaxMonitorBytes) {
                    reply->setProperty("tooLarge", true);
                    reply->abort();
                }
            });
        }

        connect(reply, &QNetworkReply::finished, this, [this, reply]() {
            m_activeReplies.removeAll(reply);
            reply->deleteLater();

            const QString requestType = reply->property("requestType").toString();
            // forOpenPage may have been raised while the request was in flight
            const Request finishedRequest{reply->request().url(), requestType, reply->property("forOpenPage").toBool()};
            const bool timedOut = reply->property("timedOut").toBool();
            const int httpStatus = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
            const QString contentType = reply->header(QNetworkRequest::ContentTypeHeader).toString();
            const QByteArray data = reply->readAll();
            // A fast link delivers everything before the limit gets a chance to abort
            const bool tooLarge = reply->property("tooLarge").toBool() || (requestType == projectMonitorRequestType() && data.size() > MaxMonitorBytes);

            if (m_activeRequests > 0) {
                --m_activeRequests;
            }
            // Not lazy any more when somebody else asked for the same meanwhile
            const bool lazy = reply->property("lazy").toBool();
            if (lazy && m_activeLazyRequests > 0) {
                --m_activeLazyRequests;
            }

            // What is rejected as a whole is not worth parsing
            QJsonParseError parseError;
            const QJsonDocument doc = timedOut || tooLarge ? QJsonDocument() : QJsonDocument::fromJson(data, &parseError);
            // API errors come as {"error": "..."} with a 4xx/5xx status
            const QString apiError = doc.object().value(QStringLiteral("error")).toString();

            QString errorMessage;
            // A monitor answer is {"packages": [...]}, a single project is the object itself,
            // every other one {"items": [...], "meta": {...}}
            const QString payloadKey = requestType == projectMonitorRequestType() ? QStringLiteral("packages") : QStringLiteral("items");
            const bool isProjectLookup = requestType == QStringLiteral("getProject");

            if (isProjectLookup && httpStatus == 404 && !apiError.isEmpty()) {
                // An answer, not a failure: there is no project of that name
                qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR project lookup:" << apiError;
                Q_EMIT projectNotFound(queryItem(finishedRequest.url, QStringLiteral("ownername")),
                                       queryItem(finishedRequest.url, QStringLiteral("projectname")));
                processNextRequest();
                return;
            }

            if (timedOut) {
                errorMessage = i18n("The COPR request timed out.");
            } else if (tooLarge) {
                errorMessage = i18n("This COPR project has too many packages to check them all.");
            } else if (httpStatus == 429 || httpStatus == 503) {
                noteRetryAfter(reply);
                errorMessage = i18n("COPR is temporarily not accepting requests (HTTP %1). Try again later.", QString::number(httpStatus));
            } else if (httpStatus >= 400) {
                // Qt's error string for HTTP errors repeats the whole request URL: log only
                qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR HTTP error for" << requestType << "-" << reply->errorString();
                errorMessage = apiError.isEmpty() ? i18n("COPR returned HTTP %1.", QString::number(httpStatus))
                                                  : i18n("COPR reported an error (HTTP %1): %2", QString::number(httpStatus), apiError);
            } else if (reply->error() != QNetworkReply::NoError) {
                errorMessage = i18n("Network error: %1", reply->errorString());
            } else if (contentType.startsWith(QLatin1String("text/html"), Qt::CaseInsensitive) || data.trimmed().startsWith('<')) {
                // The bot protection in front of COPR answers HTTP 200 with an HTML challenge page
                errorMessage = i18n("COPR answered with a web page instead of API data, most likely its bot protection. Try again later.");
            } else if (!isJsonMediaType(contentType)) {
                qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG)
                    << "Unexpected content type from COPR for" << requestType << "- content type:" << contentType << "- data:" << data.left(200);
                errorMessage = i18n("Invalid response from the COPR API.");
            } else if (!doc.isObject()) {
                qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Invalid JSON from COPR for" << requestType << "- error:" << parseError.errorString()
                                                              << "- content type:" << contentType << "- data:" << data.left(200);
                errorMessage = i18n("Invalid response from the COPR API.");
            } else if (isProjectLookup ? !doc.object().value(QStringLiteral("name")).isString() : !doc.object().value(payloadKey).isArray()) {
                // Without the array this is not a result, and it must not look like an empty one
                qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR answer without items for" << requestType << "- data:" << data.left(200);
                errorMessage = apiError.isEmpty() ? i18n("Invalid response from the COPR API.") : i18n("COPR reported an error: %1", apiError);
            }

            if (lazy) {
                noteLazyResult(!errorMessage.isEmpty());
            }
            if (!errorMessage.isEmpty()) {
                failRequest(finishedRequest, errorMessage);
                processNextRequest();
                return;
            }

            const QJsonObject json = doc.object();

            // Cache the successful response
            storeInCache(finishedRequest, json, data.size());

            emitResultForRequest(finishedRequest, json);

            processNextRequest();
        });
    }
}

QString CoprClient::convertMarkdownToHtml(const QString &markdown) const
{
#if defined(WITH_MARKDOWN)
    const QByteArray markdownBytes = markdown.toUtf8();
    MMIOT *markdownHandle = mkd_string(markdownBytes.constData(), markdownBytes.size(), {});

#ifdef MARKDOWN3
    mkd_flag_t *flags = mkd_flags();
    mkd_set_flag_num(flags, MKD_FENCEDCODE);
    mkd_set_flag_num(flags, MKD_GITHUBTAGS);
    mkd_set_flag_num(flags, MKD_AUTOLINK);
    mkd_set_flag_num(flags, MKD_SAFELINK);
    mkd_set_flag_num(flags, MKD_NOHTML);
    const bool compiled = mkd_compile(markdownHandle, flags);
#else
    const bool compiled = mkd_compile(markdownHandle, MKD_FENCEDCODE | MKD_GITHUBTAGS | MKD_AUTOLINK | MKD_SAFELINK | MKD_NOHTML);
#endif
    if (compiled) {
        char *htmlDocument = nullptr;
        const int size = mkd_document(markdownHandle, &htmlDocument);
        const QString html = QString::fromUtf8(htmlDocument, size);
        mkd_cleanup(markdownHandle);
#ifdef MARKDOWN3
        mkd_free_flags(flags);
#endif
        return html;
    }
    mkd_cleanup(markdownHandle);
#ifdef MARKDOWN3
    mkd_free_flags(flags);
#endif
#endif

    QString html = markdown.toHtmlEscaped();

    // Convert image badges with nested links like [![alt](image)](url) to clickable images
    html.replace(QRegularExpression(QStringLiteral("\\[!\\[([^\\]]*)\\]\\(([^\\)]+)\\)\\]\\(([^\\)]+)\\)")),
                 QStringLiteral("<a href=\"\\3\"><img src=\"\\2\" alt=\"\\1\" height=\"20\"></a>"));

    // Convert simple image badges like ![alt](url) to images
    html.replace(QRegularExpression(QStringLiteral("!\\[([^\\]]*)\\]\\(([^\\)]+)\\)")), QStringLiteral("<img src=\"\\2\" alt=\"\\1\" height=\"20\">"));

    // Convert markdown links [text](url) to HTML links
    html.replace(QRegularExpression(QStringLiteral("\\[([^\\]]+)\\]\\(([^\\)]+)\\)")), QStringLiteral("<a href=\"\\2\">\\1</a>"));

    // Convert headers (###, ##, #) to bold with sizes
    html.replace(QRegularExpression(QStringLiteral("^#{3}\\s+(.*)$"), QRegularExpression::MultilineOption), QStringLiteral("<b>\\1</b>"));
    html.replace(QRegularExpression(QStringLiteral("^#{2}\\s+(.*)$"), QRegularExpression::MultilineOption),
                 QStringLiteral("<b style='font-size: 110%;'>\\1</b>"));
    html.replace(QRegularExpression(QStringLiteral("^#\\s+(.*)$"), QRegularExpression::MultilineOption), QStringLiteral("<b style='font-size: 120%;'>\\1</b>"));

    // Convert **text** to bold
    html.replace(QRegularExpression(QStringLiteral("\\*\\*([^\\*]+)\\*\\*")), QStringLiteral("<b>\\1</b>"));

    // Convert `code` to monospace
    html.replace(QRegularExpression(QStringLiteral("`([^`]+)`")), QStringLiteral("<code>\\1</code>"));

    // Convert line breaks, but keep paragraph spacing
    html.replace(QStringLiteral("\n\n"), QStringLiteral("<br><br>"));
    html.replace(QStringLiteral("\n"), QStringLiteral("<br>"));

    return html;
}

static QStringList jsonStringArray(const QJsonArray &array)
{
    QStringList values;
    values.reserve(array.size());

    for (const QJsonValue &value : array) {
        const QString text = value.toString();
        if (!text.isEmpty()) {
            values.append(text);
        }
    }

    return values;
}

static QString jsonValueToDisplayString(const QJsonValue &value)
{
    if (value.isString()) {
        return value.toString();
    }
    if (value.isDouble()) {
        return QString::number(value.toInt());
    }
    if (value.isBool()) {
        return value.toBool() ? QStringLiteral("true") : QStringLiteral("false");
    }
    return {};
}

static QDateTime unixTimestampToDateTime(const QJsonValue &value)
{
    const qint64 timestamp = value.toVariant().toLongLong();
    if (timestamp <= 0) {
        return {};
    }
    return QDateTime::fromSecsSinceEpoch(timestamp);
}

static QString sourceUrlFromSourceDict(const QJsonObject &source)
{
    const QString url = source.value(QStringLiteral("url")).toString();
    if (!url.isEmpty()) {
        return url;
    }

    const QString cloneUrl = source.value(QStringLiteral("clone_url")).toString();
    if (!cloneUrl.isEmpty()) {
        return cloneUrl;
    }

    return {};
}

CoprProjectInfo CoprClient::parseProjectObject(const QJsonObject &obj)
{
    CoprProjectInfo project;
    project.owner = obj.value(QStringLiteral("ownername")).toString();
    project.name = obj.value(QStringLiteral("name")).toString();
    project.fullName = obj.value(QStringLiteral("full_name")).toString();
    project.description = convertMarkdownToHtml(obj.value(QStringLiteral("description")).toString());
    project.instructions = convertMarkdownToHtml(obj.value(QStringLiteral("instructions")).toString());
    project.contact = obj.value(QStringLiteral("contact")).toString();
    project.id = obj.value(QStringLiteral("id")).toInt();
    project.homepage = obj.value(QStringLiteral("homepage")).toString();
    project.additionalRepos = jsonStringArray(obj.value(QStringLiteral("additional_repos")).toArray());
    project.repoPriority = jsonValueToDisplayString(obj.value(QStringLiteral("repo_priority")));
    project.appstream = obj.value(QStringLiteral("appstream")).toBool();
    project.develMode = obj.value(QStringLiteral("devel_mode")).toBool();
    project.enableNet = obj.value(QStringLiteral("enable_net")).toBool();
    project.followFedoraBranching = obj.value(QStringLiteral("follow_fedora_branching")).toBool();
    project.autoPrune = obj.value(QStringLiteral("auto_prune")).toBool();
    project.moduleHotfixes = obj.value(QStringLiteral("module_hotfixes")).toBool();
    project.unlistedOnHomepage = obj.value(QStringLiteral("unlisted_on_hp")).toBool();

    const QJsonObject chrootRepos = obj.value(QStringLiteral("chroot_repos")).toObject();
    if (!chrootRepos.isEmpty()) {
        project.chroots = chrootRepos.keys();
    } else {
        project.chroots = jsonStringArray(obj.value(QStringLiteral("chroots")).toArray());
    }

    return project;
}

QList<CoprProjectInfo> CoprClient::parseProjectsResponse(const QJsonObject &json)
{
    QList<CoprProjectInfo> projects;

    QJsonArray items = json.value(QStringLiteral("items")).toArray();

    for (const QJsonValue &value : items) {
        projects.append(parseProjectObject(value.toObject()));
    }

    return projects;
}

QList<CoprPackageInfo> CoprClient::parsePackagesResponse(const QJsonObject &json, const QString &owner, const QString &project)
{
    QList<CoprPackageInfo> packages;

    QJsonArray items = json.value(QStringLiteral("items")).toArray();

    for (const QJsonValue &value : items) {
        QJsonObject obj = value.toObject();

        CoprPackageInfo package;
        package.name = obj.value(QStringLiteral("name")).toString();
        package.owner = owner;
        package.projectName = project;
        package.sourceType = obj.value(QStringLiteral("source_type")).toString();

        // The state shown is the one of the last build, while the version and the dates
        // are those of the last build that succeeded: that is what can be installed.
        // The chroots of a build are those it was submitted for, with no result per
        // chroot, and the last build says nothing about older ones that are still
        // published. Availability is therefore never derived here, the monitor has it.
        const QJsonObject builds = obj.value(QStringLiteral("builds")).toObject();
        const QJsonObject lastBuild = builds.value(QStringLiteral("latest")).toObject();
        QJsonObject latestBuild = builds.value(QStringLiteral("latest_succeeded")).toObject();
        if (latestBuild.isEmpty()) {
            latestBuild = lastBuild;
        }

        if (!latestBuild.isEmpty()) {
            package.latestBuildState = (lastBuild.isEmpty() ? latestBuild : lastBuild).value(QStringLiteral("state")).toString();
            package.latestBuildRepoUrl = latestBuild.value(QStringLiteral("repo_url")).toString();
            package.latestBuildSubmitter = latestBuild.value(QStringLiteral("submitter")).toString();
            package.latestBuildSubmittedOn = unixTimestampToDateTime(latestBuild.value(QStringLiteral("submitted_on")));
            package.latestBuildStartedOn = unixTimestampToDateTime(latestBuild.value(QStringLiteral("started_on")));
            package.latestBuildEndedOn = unixTimestampToDateTime(latestBuild.value(QStringLiteral("ended_on")));

            const QJsonObject sourcePackage = latestBuild.value(QStringLiteral("source_package")).toObject();
            package.version = sourcePackage.value(QStringLiteral("version")).toString();
        }

        // Get source info if available
        QJsonObject source = obj.value(QStringLiteral("source_dict")).toObject();
        if (!source.isEmpty()) {
            package.sourceUrl = sourceUrlFromSourceDict(source);
            package.sourceSpec = source.value(QStringLiteral("spec")).toString();
            package.sourceSubdirectory = source.value(QStringLiteral("subdirectory")).toString();
            if (package.homepage.isEmpty()) {
                package.homepage = package.sourceUrl;
            }
        }

        packages.append(package);
    }

    return packages;
}

// {"packages": [{"name": ..., "chroots": {"<chroot>": {"state", "status", "build_id", "pkg_version"}}}]}
// with the last build of every package in every chroot that is enabled in the project.
// Packages that were never built are not listed.
QList<CoprPackageInfo> CoprClient::parseMonitorResponse(const QJsonObject &json, const QString &owner, const QString &project, bool *complete)
{
    // "forked" is a build copied from another project together with its results.
    // "skipped" is not in this list: besides "already built" the server also uses
    // it for a chroot that ExclusiveArch or ExcludeArch left without any package.
    static const QStringList installableStates = {QStringLiteral("succeeded"), QStringLiteral("forked")};

    QList<CoprPackageInfo> packages;
    const QJsonArray items = json.value(QStringLiteral("packages")).toArray();
    *complete = items.size() <= MaxPackagesPerProject;

    // Of a project that is too large keep the beginning and the package that would be
    // chosen by default: the first one named like the project that may be installable
    // here, or else the first one named like it. When it comes later, the last place is
    // left for it
    qsizetype namedIndex = -1;
    if (!*complete) {
        for (qsizetype i = 0; i < items.size(); ++i) {
            const QJsonObject obj = items.at(i).toObject();
            if (obj.value(QStringLiteral("name")).toString().compare(project, Qt::CaseInsensitive) != 0) {
                continue;
            }
            if (m_currentChroot.isEmpty() || obj.value(QStringLiteral("chroots")).toObject().contains(m_currentChroot)) {
                namedIndex = i;
                break;
            }
            if (namedIndex < 0) {
                namedIndex = i;
            }
        }
    }
    const qsizetype keptFromBeginning = namedIndex >= MaxPackagesPerProject ? MaxPackagesPerProject - 1 : MaxPackagesPerProject;

    for (qsizetype i = 0; i < items.size(); ++i) {
        if (i >= keptFromBeginning && i != namedIndex) {
            continue;
        }

        const QJsonObject obj = items.at(i).toObject();
        const QString name = obj.value(QStringLiteral("name")).toString();

        CoprPackageInfo package;
        package.name = name;
        package.owner = owner;
        package.projectName = project;

        const QJsonObject chroots = obj.value(QStringLiteral("chroots")).toObject();
        QString anyVersion;
        for (auto it = chroots.constBegin(); it != chroots.constEnd(); ++it) {
            const QJsonObject chroot = it.value().toObject();
            if (installableStates.contains(chroot.value(QStringLiteral("state")).toString())) {
                package.availableChroots.append(it.key());
                if (anyVersion.isEmpty()) {
                    anyVersion = chroot.value(QStringLiteral("pkg_version")).toString();
                }
            }
        }

        if (m_currentChroot.isEmpty()) {
            package.version = anyVersion;
        } else if (!chroots.contains(m_currentChroot)) {
            package.availability = CoprAvailability::NotAvailable;
        } else {
            const QJsonObject chroot = chroots.value(m_currentChroot).toObject();
            package.currentChrootState = chroot.value(QStringLiteral("state")).toString();
            package.version = chroot.value(QStringLiteral("pkg_version")).toString();
            package.availability = installableStates.contains(package.currentChrootState) ? CoprAvailability::Available : CoprAvailability::NotConfirmed;
        }

        packages.append(package);
    }

    return packages;
}
