#include "CoprClient.h"
#include "libdiscover_backend_packagekit_debug.h"

#include <KLocalizedString>
#include <KOSRelease>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QLocale>
#include <QNetworkRequest>
#include <QRegularExpression>
#include <QSettings>
#include <QSysInfo>
#include <QTimeZone>
#include <QTimer>
#include <QUrl>
#include <QUrlQuery>

namespace DiscoverVersion
{
// contains the static QLatin1String version definition
// autogenerated from top CMakeLists.txt
#include "DiscoverVersion.h"
}

#if defined(WITH_MARKDOWN)
extern "C" {
#include <mkdio.h>
}
#endif

// The only place that knows where COPR lives
static QString coprHubUrl()
{
    return QStringLiteral("https://copr.fedorainfracloud.org");
}

static QByteArray coprUserAgent()
{
    return QByteArrayLiteral("DiscoverPlus/") + QByteArray(DiscoverVersion::version.data(), DiscoverVersion::version.size())
        + QByteArrayLiteral(" (+https://github.com/DXVSI/discover-plus)");
}

// Maps QSysInfo::currentCpuArchitecture() to the RPM basearch used in chroot names
static QString rpmBaseArch(const QString &cpuArchitecture)
{
    if (cpuArchitecture == QLatin1String("arm64")) {
        return QStringLiteral("aarch64");
    }
    if (cpuArchitecture == QLatin1String("arm")) {
        return QStringLiteral("armhfp");
    }
    if (cpuArchitecture == QLatin1String("power64")) {
        return QSysInfo::ByteOrder == QSysInfo::LittleEndian ? QStringLiteral("ppc64le") : QStringLiteral("ppc64");
    }

    static const QStringList sameInRpm = {
        QStringLiteral("x86_64"),
        QStringLiteral("i386"),
        QStringLiteral("s390x"),
        QStringLiteral("riscv64"),
        QStringLiteral("loongarch64"),
    };
    return sameInRpm.contains(cpuArchitecture) ? cpuArchitecture : QString();
}

// The dnf copr plugin lets a distribution declare which COPR chroots it uses:
// [main] distribution and releasever, read in this order, later files win
static void readDnfCoprOverrides(QString &distribution, QString &releasever)
{
    QStringList files = {
        QStringLiteral("/usr/share/dnf/plugins/copr.vendor.conf"),
        QStringLiteral("/etc/dnf/plugins/copr.vendor.conf"),
        QStringLiteral("/etc/dnf/plugins/copr.conf"),
    };
    const QDir dropInDir(QStringLiteral("/etc/dnf/plugins/copr.d"));
    const QStringList dropIns = dropInDir.entryList({QStringLiteral("*.conf")}, QDir::Files, QDir::Name);
    for (const QString &dropIn : dropIns) {
        files.append(dropInDir.filePath(dropIn));
    }

    for (const QString &file : std::as_const(files)) {
        if (!QFile::exists(file)) {
            continue;
        }
        const QSettings config(file, QSettings::IniFormat);
        const QString fileDistribution = config.value(QStringLiteral("main/distribution")).toString().trimmed();
        if (!fileDistribution.isEmpty()) {
            distribution = fileDistribution;
        }
        const QString fileReleasever = config.value(QStringLiteral("main/releasever")).toString().trimmed();
        if (!fileReleasever.isEmpty()) {
            releasever = fileReleasever;
        }
    }
}

CoprClient::CoprClient(QObject *parent)
    : QObject(parent)
    , m_baseUrl(coprHubUrl() + QStringLiteral("/api_3"))
    , m_networkAccessManager(new QNetworkAccessManager(this))
{
    m_currentChroot = detectCurrentChroot();

    if (m_currentChroot.isEmpty()) {
        qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient: could not detect the COPR chroot of this system (os-release ID:" << KOSRelease().id()
                                                      << "VERSION_ID:" << KOSRelease().versionId() << "CPU:" << QSysInfo::currentCpuArchitecture()
                                                      << "). A distribution other than fedora is only trusted when it is declared in the dnf copr plugin"
                                                      << "configuration. COPR availability is unknown: projects are not filtered and installs are not blocked.";
    } else {
        qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient initialized. Chroot:" << m_currentChroot;
    }
}

CoprClient::~CoprClient()
{
    cancelAllRequests();
}

// Same logic as the dnf5 copr plugin (copr_config.cpp): <distribution>-<releasever>-<arch>
// from the plugin configuration, else from os-release, where Fedora Rawhide is
// recognised by REDHAT_SUPPORT_PRODUCT_VERSION because its VERSION_ID is numeric.
// dnf5 hands that name to the server, which picks the chroot. We compare it with
// chroot names ourselves, so an os-release ID of a Fedora derivative ("nobara-42")
// would match nothing, hide every project and refuse every install. Only "fedora"
// and what the distribution itself declared for dnf are trusted; anything else
// is an unknown chroot.
QString CoprClient::detectCurrentChroot() const
{
    QString distribution;
    QString releasever;
    readDnfCoprOverrides(distribution, releasever);

    const KOSRelease osRelease;
    if (distribution.isEmpty()) {
        distribution = osRelease.id();
        if (distribution != QLatin1String("fedora")) {
            return {};
        }
    }
    if (releasever.isEmpty()) {
        releasever = osRelease.versionId();
        if (distribution == QLatin1String("fedora") && osRelease.extraValue(QStringLiteral("REDHAT_SUPPORT_PRODUCT_VERSION")) == QLatin1String("rawhide")) {
            releasever = QStringLiteral("rawhide");
        }
    }

    const QString arch = rpmBaseArch(QSysInfo::currentCpuArchitecture());
    if (releasever.isEmpty() || arch.isEmpty()) {
        return {};
    }

    return QStringLiteral("%1-%2-%3").arg(distribution, releasever, arch);
}

QUrl CoprClient::projectWebUrl(const QString &owner, const QString &project)
{
    // Group projects are owned by "@group" in the API but live under /coprs/g/<group>/
    if (owner.startsWith(QLatin1Char('@'))) {
        return QUrl(QStringLiteral("%1/coprs/g/%2/%3/").arg(coprHubUrl(), owner.mid(1), project));
    }
    return QUrl(QStringLiteral("%1/coprs/%2/%3/").arg(coprHubUrl(), owner, project));
}

void CoprClient::searchProjects(const QString &query, int limit, int offset)
{
    QString endpoint = QStringLiteral("/project/search");
    QUrl url(m_baseUrl + endpoint);

    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("query"), query);
    urlQuery.addQueryItem(QStringLiteral("limit"), QString::number(limit));
    urlQuery.addQueryItem(QStringLiteral("offset"), QString::number(offset));
    url.setQuery(urlQuery);

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient: Searching projects, query:" << query << "limit:" << limit << "offset:" << offset;
    queueRequest(url, QStringLiteral("searchProjects"));
}

void CoprClient::getLatestProjects(int limit, int offset)
{
    QString endpoint = QStringLiteral("/project/list");
    QUrl url(m_baseUrl + endpoint);

    // The server defaults to order_type=ASC (the oldest projects), so the
    // order has to be explicit. There is no server-side maximum for limit.
    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("limit"), QString::number(limit));
    urlQuery.addQueryItem(QStringLiteral("offset"), QString::number(offset));
    urlQuery.addQueryItem(QStringLiteral("order"), QStringLiteral("id"));
    urlQuery.addQueryItem(QStringLiteral("order_type"), QStringLiteral("DESC"));
    url.setQuery(urlQuery);

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "CoprClient: Getting latest projects:" << url.toString();
    queueRequest(url, QStringLiteral("getLatestProjects"));
}

void CoprClient::getProjectPackages(const QString &owner, const QString &project)
{
    QString endpoint = QStringLiteral("/package/list");
    QUrl url(m_baseUrl + endpoint);

    QUrlQuery urlQuery;
    urlQuery.addQueryItem(QStringLiteral("ownername"), owner);
    urlQuery.addQueryItem(QStringLiteral("projectname"), project);
    urlQuery.addQueryItem(QStringLiteral("with_latest_build"), QStringLiteral("True"));
    urlQuery.addQueryItem(QStringLiteral("limit"), QStringLiteral("10"));
    url.setQuery(urlQuery);

    queueRequest(url, QStringLiteral("getProjectPackages:") + owner + QStringLiteral(":") + project);
}

void CoprClient::cancelAllRequests()
{
    for (const auto &reply : std::as_const(m_activeReplies)) {
        if (reply) {
            reply->disconnect(this);
            reply->abort();
            reply->deleteLater();
        }
    }
    m_activeReplies.clear();
    m_requestQueue.clear();
    m_activeRequests = 0;

    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Cancelled all COPR pending requests";
}

void CoprClient::queueRequest(const QUrl &url, const QString &requestType)
{
    QString urlString = url.toString();

    // Check cache first
    if (m_cache.contains(urlString)) {
        const CacheEntry &entry = m_cache[urlString];
        qint64 now = QDateTime::currentMSecsSinceEpoch();
        if (now - entry.timestamp < CacheTtlMs) {
            qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR cache hit for:" << requestType;
            QTimer::singleShot(0, this, [this, requestType, json = entry.data]() {
                emitResultForRequest(requestType, json);
            });
            return;
        }
        m_cache.remove(urlString);
    }

    // The server asked us to back off (HTTP 429/503): do not send anything until then
    const qint64 retryInMs = m_retryNotBeforeMs - QDateTime::currentMSecsSinceEpoch();
    if (retryInMs > 0) {
        const int retryInSecs = int((retryInMs + 999) / 1000);
        QTimer::singleShot(0, this, [this, requestType, retryInSecs]() {
            failRequest(requestType,
                        i18np("COPR asked to wait before sending more requests. Try again in %1 second.",
                              "COPR asked to wait before sending more requests. Try again in %1 seconds.",
                              retryInSecs));
        });
        return;
    }

    // Deduplication - skip if same URL already queued
    for (const auto &queued : m_requestQueue) {
        if (queued.first == url) {
            qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR request deduped:" << requestType;
            return;
        }
    }

    m_requestQueue.enqueue(qMakePair(url, requestType));
    qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Queued COPR request:" << requestType << "queue size:" << m_requestQueue.size();

    if (m_activeRequests < MaxConcurrentRequests) {
        processNextRequest();
    }
}

void CoprClient::emitResultForRequest(const QString &requestType, const QJsonObject &json)
{
    if (requestType == QStringLiteral("searchProjects") || requestType == QStringLiteral("getLatestProjects")) {
        Q_EMIT projectsFound(parseProjectsResponse(json));
    } else if (requestType.startsWith(QStringLiteral("getProjectPackages:"))) {
        QStringList parts = requestType.split(QLatin1Char(':'));
        if (parts.size() >= 3) {
            const QList<CoprPackageInfo> packages = parsePackagesResponse(json, parts[1], parts[2]);
            Q_EMIT projectPackagesFound(parts[1], parts[2], packages);
        }
    }
}

void CoprClient::emitEmptyResultForRequest(const QString &requestType)
{
    if (requestType == QStringLiteral("searchProjects") || requestType == QStringLiteral("getLatestProjects")) {
        Q_EMIT projectsFound(QList<CoprProjectInfo>());
    } else if (requestType.startsWith(QStringLiteral("getProjectPackages:"))) {
        const QStringList parts = requestType.split(QLatin1Char(':'));
        if (parts.size() >= 3) {
            Q_EMIT projectPackagesFound(parts[1], parts[2], QList<CoprPackageInfo>());
        }
    }
}

void CoprClient::failRequest(const QString &requestType, const QString &errorMessage)
{
    qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR request" << requestType << "failed:" << errorMessage;
    Q_EMIT errorOccurred(requestType, errorMessage);
    emitEmptyResultForRequest(requestType);
}

void CoprClient::noteRetryAfter(const QNetworkReply *reply)
{
    // Retry-After is either a number of seconds or an HTTP date
    const QByteArray retryAfter = reply->rawHeader("Retry-After").trimmed();
    const qint64 now = QDateTime::currentMSecsSinceEpoch();

    bool isNumber = false;
    qint64 seconds = retryAfter.toLongLong(&isNumber);
    if (!isNumber) {
        QString httpDate = QString::fromLatin1(retryAfter);
        httpDate.chop(httpDate.endsWith(QLatin1String(" GMT")) ? 4 : 0);
        QDateTime date = QLocale::c().toDateTime(httpDate, QStringLiteral("ddd, dd MMM yyyy hh:mm:ss"));
        date.setTimeZone(QTimeZone::UTC);
        seconds = date.isValid() ? (date.toMSecsSinceEpoch() - now) / 1000 : DefaultRetryAfterSecs;
    }

    seconds = qBound(qint64(1), seconds, qint64(MaxRetryAfterSecs));
    m_retryNotBeforeMs = qMax(m_retryNotBeforeMs, now + seconds * 1000);
    qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "COPR asked to back off, Retry-After:" << retryAfter << "- no COPR requests for" << seconds << "s";
}

void CoprClient::processNextRequest()
{
    while (!m_requestQueue.isEmpty() && m_activeRequests < MaxConcurrentRequests) {
        const auto requestData = m_requestQueue.dequeue();
        const QUrl url = requestData.first;
        const QString requestType = requestData.second;
        const QString urlString = url.toString();

        QNetworkRequest request(url);
        request.setRawHeader("Accept", "application/json");
        // Identify ourselves: without it Qt sends "Mozilla/5.0", which the COPR bot protection treats as a browser
        request.setHeader(QNetworkRequest::UserAgentHeader, coprUserAgent());

        QNetworkReply *reply = m_networkAccessManager->get(request);
        reply->setProperty("requestType", requestType);
        reply->setProperty("urlString", urlString);

        m_activeReplies.append(reply);
        ++m_activeRequests;

        qCDebug(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Processing COPR request via Qt network:" << requestType << "active:" << m_activeRequests
                                                    << "queued:" << m_requestQueue.size();

        // Search costs the server 6-8 s; a project list page is a few hundred KB (about 3 s on a good link)
        int timeoutMs = 10000;
        if (requestType == QStringLiteral("searchProjects")) {
            timeoutMs = 25000;
        } else if (requestType == QStringLiteral("getLatestProjects")) {
            timeoutMs = 20000;
        }
        QTimer::singleShot(timeoutMs, reply, [reply]() {
            if (reply->isRunning()) {
                reply->setProperty("timedOut", true);
                reply->abort();
            }
        });

        connect(reply, &QNetworkReply::finished, this, [this, reply]() {
            m_activeReplies.removeAll(reply);
            reply->deleteLater();

            const QString requestType = reply->property("requestType").toString();
            const QString urlString = reply->property("urlString").toString();
            const bool timedOut = reply->property("timedOut").toBool();
            const int httpStatus = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
            const QString contentType = reply->header(QNetworkRequest::ContentTypeHeader).toString();
            const QByteArray data = reply->readAll();

            if (m_activeRequests > 0) {
                --m_activeRequests;
            }

            QJsonParseError parseError;
            const QJsonDocument doc = QJsonDocument::fromJson(data, &parseError);
            // API errors come as {"error": "..."} with a 4xx/5xx status
            const QString apiError = doc.object().value(QStringLiteral("error")).toString();

            QString errorMessage;
            if (timedOut) {
                errorMessage = i18n("The COPR request timed out.");
            } else if (httpStatus == 429 || httpStatus == 503) {
                noteRetryAfter(reply);
                errorMessage = i18n("COPR is temporarily not accepting requests (HTTP %1). Try again later.", QString::number(httpStatus));
            } else if (reply->error() != QNetworkReply::NoError || httpStatus >= 400) {
                errorMessage = apiError.isEmpty() ? i18n("COPR request failed: %1", reply->errorString())
                                                  : i18n("COPR reported an error (HTTP %1): %2", QString::number(httpStatus), apiError);
            } else if (contentType.startsWith(QLatin1String("text/html"), Qt::CaseInsensitive) || data.trimmed().startsWith('<')) {
                // The bot protection in front of COPR answers HTTP 200 with an HTML challenge page
                errorMessage = i18n("COPR answered with a web page instead of API data, most likely its bot protection. Try again later.");
            } else if (!doc.isObject()) {
                qCWarning(LIBDISCOVER_BACKEND_PACKAGEKIT_LOG) << "Invalid JSON from COPR for" << requestType << "- error:" << parseError.errorString()
                                                              << "- content type:" << contentType << "- data:" << data.left(200);
                errorMessage = i18n("Invalid response from the COPR API.");
            }

            if (!errorMessage.isEmpty()) {
                failRequest(requestType, errorMessage);
                processNextRequest();
                return;
            }

            const QJsonObject json = doc.object();

            // Cache the successful response
            m_cache[urlString] = CacheEntry{json, QDateTime::currentMSecsSinceEpoch()};

            emitResultForRequest(requestType, json);

            processNextRequest();
        });
    }
}

QString CoprClient::convertMarkdownToHtml(const QString &markdown) const
{
#if defined(WITH_MARKDOWN)
    const QByteArray markdownBytes = markdown.toUtf8();
    MMIOT *markdownHandle = mkd_string(markdownBytes.constData(), markdownBytes.size(), {});

#ifdef MARKDOWN3
    mkd_flag_t *flags = mkd_flags();
    mkd_set_flag_num(flags, MKD_FENCEDCODE);
    mkd_set_flag_num(flags, MKD_GITHUBTAGS);
    mkd_set_flag_num(flags, MKD_AUTOLINK);
    mkd_set_flag_num(flags, MKD_SAFELINK);
    mkd_set_flag_num(flags, MKD_NOHTML);
    const bool compiled = mkd_compile(markdownHandle, flags);
#else
    const bool compiled = mkd_compile(markdownHandle, MKD_FENCEDCODE | MKD_GITHUBTAGS | MKD_AUTOLINK | MKD_SAFELINK | MKD_NOHTML);
#endif
    if (compiled) {
        char *htmlDocument = nullptr;
        const int size = mkd_document(markdownHandle, &htmlDocument);
        const QString html = QString::fromUtf8(htmlDocument, size);
        mkd_cleanup(markdownHandle);
#ifdef MARKDOWN3
        mkd_free_flags(flags);
#endif
        return html;
    }
    mkd_cleanup(markdownHandle);
#ifdef MARKDOWN3
    mkd_free_flags(flags);
#endif
#endif

    QString html = markdown.toHtmlEscaped();

    // Convert image badges with nested links like [![alt](image)](url) to clickable images
    html.replace(QRegularExpression(QStringLiteral("\\[!\\[([^\\]]*)\\]\\(([^\\)]+)\\)\\]\\(([^\\)]+)\\)")),
                 QStringLiteral("<a href=\"\\3\"><img src=\"\\2\" alt=\"\\1\" height=\"20\"></a>"));

    // Convert simple image badges like ![alt](url) to images
    html.replace(QRegularExpression(QStringLiteral("!\\[([^\\]]*)\\]\\(([^\\)]+)\\)")), QStringLiteral("<img src=\"\\2\" alt=\"\\1\" height=\"20\">"));

    // Convert markdown links [text](url) to HTML links
    html.replace(QRegularExpression(QStringLiteral("\\[([^\\]]+)\\]\\(([^\\)]+)\\)")), QStringLiteral("<a href=\"\\2\">\\1</a>"));

    // Convert headers (###, ##, #) to bold with sizes
    html.replace(QRegularExpression(QStringLiteral("^#{3}\\s+(.*)$"), QRegularExpression::MultilineOption), QStringLiteral("<b>\\1</b>"));
    html.replace(QRegularExpression(QStringLiteral("^#{2}\\s+(.*)$"), QRegularExpression::MultilineOption),
                 QStringLiteral("<b style='font-size: 110%;'>\\1</b>"));
    html.replace(QRegularExpression(QStringLiteral("^#\\s+(.*)$"), QRegularExpression::MultilineOption), QStringLiteral("<b style='font-size: 120%;'>\\1</b>"));

    // Convert **text** to bold
    html.replace(QRegularExpression(QStringLiteral("\\*\\*([^\\*]+)\\*\\*")), QStringLiteral("<b>\\1</b>"));

    // Convert `code` to monospace
    html.replace(QRegularExpression(QStringLiteral("`([^`]+)`")), QStringLiteral("<code>\\1</code>"));

    // Convert line breaks, but keep paragraph spacing
    html.replace(QStringLiteral("\n\n"), QStringLiteral("<br><br>"));
    html.replace(QStringLiteral("\n"), QStringLiteral("<br>"));

    return html;
}

static QStringList jsonStringArray(const QJsonArray &array)
{
    QStringList values;
    values.reserve(array.size());

    for (const QJsonValue &value : array) {
        const QString text = value.toString();
        if (!text.isEmpty()) {
            values.append(text);
        }
    }

    return values;
}

static QString jsonValueToDisplayString(const QJsonValue &value)
{
    if (value.isString()) {
        return value.toString();
    }
    if (value.isDouble()) {
        return QString::number(value.toInt());
    }
    if (value.isBool()) {
        return value.toBool() ? QStringLiteral("true") : QStringLiteral("false");
    }
    return {};
}

static QDateTime unixTimestampToDateTime(const QJsonValue &value)
{
    const qint64 timestamp = value.toVariant().toLongLong();
    if (timestamp <= 0) {
        return {};
    }
    return QDateTime::fromSecsSinceEpoch(timestamp);
}

static QString sourceUrlFromSourceDict(const QJsonObject &source)
{
    const QString url = source.value(QStringLiteral("url")).toString();
    if (!url.isEmpty()) {
        return url;
    }

    const QString cloneUrl = source.value(QStringLiteral("clone_url")).toString();
    if (!cloneUrl.isEmpty()) {
        return cloneUrl;
    }

    return {};
}

CoprProjectInfo CoprClient::parseProjectObject(const QJsonObject &obj)
{
    CoprProjectInfo project;
    project.owner = obj.value(QStringLiteral("ownername")).toString();
    project.name = obj.value(QStringLiteral("name")).toString();
    project.fullName = obj.value(QStringLiteral("full_name")).toString();
    project.description = convertMarkdownToHtml(obj.value(QStringLiteral("description")).toString());
    project.instructions = convertMarkdownToHtml(obj.value(QStringLiteral("instructions")).toString());
    project.contact = obj.value(QStringLiteral("contact")).toString();
    project.id = obj.value(QStringLiteral("id")).toInt();
    project.homepage = obj.value(QStringLiteral("homepage")).toString();
    project.additionalRepos = jsonStringArray(obj.value(QStringLiteral("additional_repos")).toArray());
    project.repoPriority = jsonValueToDisplayString(obj.value(QStringLiteral("repo_priority")));
    project.appstream = obj.value(QStringLiteral("appstream")).toBool();
    project.develMode = obj.value(QStringLiteral("devel_mode")).toBool();
    project.enableNet = obj.value(QStringLiteral("enable_net")).toBool();
    project.followFedoraBranching = obj.value(QStringLiteral("follow_fedora_branching")).toBool();
    project.autoPrune = obj.value(QStringLiteral("auto_prune")).toBool();
    project.moduleHotfixes = obj.value(QStringLiteral("module_hotfixes")).toBool();
    project.unlistedOnHomepage = obj.value(QStringLiteral("unlisted_on_hp")).toBool();

    const QJsonObject chrootRepos = obj.value(QStringLiteral("chroot_repos")).toObject();
    if (!chrootRepos.isEmpty()) {
        project.chroots = chrootRepos.keys();
    } else {
        project.chroots = jsonStringArray(obj.value(QStringLiteral("chroots")).toArray());
    }

    return project;
}

QList<CoprProjectInfo> CoprClient::parseProjectsResponse(const QJsonObject &json)
{
    QList<CoprProjectInfo> projects;

    QJsonArray items = json.value(QStringLiteral("items")).toArray();

    for (const QJsonValue &value : items) {
        projects.append(parseProjectObject(value.toObject()));
    }

    return projects;
}

QList<CoprPackageInfo> CoprClient::parsePackagesResponse(const QJsonObject &json, const QString &owner, const QString &project)
{
    QList<CoprPackageInfo> packages;

    QJsonArray items = json.value(QStringLiteral("items")).toArray();

    for (const QJsonValue &value : items) {
        QJsonObject obj = value.toObject();

        CoprPackageInfo package;
        package.name = obj.value(QStringLiteral("name")).toString();
        package.owner = owner;
        package.projectName = project;
        package.sourceType = obj.value(QStringLiteral("source_type")).toString();

        // Extract info from latest build if available
        QJsonObject builds = obj.value(QStringLiteral("builds")).toObject();
        QJsonObject latestBuild = builds.value(QStringLiteral("latest_succeeded")).toObject();
        if (latestBuild.isEmpty()) {
            latestBuild = builds.value(QStringLiteral("latest")).toObject();
        }

        if (!latestBuild.isEmpty()) {
            // Get build chroots to determine availability
            package.availableChroots = jsonStringArray(latestBuild.value(QStringLiteral("chroots")).toArray());

            // Check if available for current Fedora
            package.isAvailableForCurrentFedora = package.availableChroots.contains(m_currentChroot);
            package.latestBuildState = latestBuild.value(QStringLiteral("state")).toString();
            package.latestBuildRepoUrl = latestBuild.value(QStringLiteral("repo_url")).toString();
            package.latestBuildSubmitter = latestBuild.value(QStringLiteral("submitter")).toString();
            package.latestBuildSubmittedOn = unixTimestampToDateTime(latestBuild.value(QStringLiteral("submitted_on")));
            package.latestBuildStartedOn = unixTimestampToDateTime(latestBuild.value(QStringLiteral("started_on")));
            package.latestBuildEndedOn = unixTimestampToDateTime(latestBuild.value(QStringLiteral("ended_on")));

            const QJsonObject sourcePackage = latestBuild.value(QStringLiteral("source_package")).toObject();
            package.version = sourcePackage.value(QStringLiteral("version")).toString();
        }

        // Get source info if available
        QJsonObject source = obj.value(QStringLiteral("source_dict")).toObject();
        if (!source.isEmpty()) {
            package.sourceUrl = sourceUrlFromSourceDict(source);
            package.sourceSpec = source.value(QStringLiteral("spec")).toString();
            package.sourceSubdirectory = source.value(QStringLiteral("subdirectory")).toString();
            if (package.homepage.isEmpty()) {
                package.homepage = package.sourceUrl;
            }
        }

        packages.append(package);
    }

    return packages;
}
